FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Определяем переменные окружения
ENV SECRET_KEY="django-insecure-uer4=dm)#om7i)7!w5dpllc%!(+-62d&=@sn#u!rkaq*^hp*_@"
ENV CELERY_BROKER_URL="redis://localhost:6379/0"
ENV CELERY_RESULT_BACKEND='redis://localhost:6379/0'

RUN mkdir -p /app/media

CMD ["celery", "-A", "config", "worker", "--loglevel=info"]